import { Inter } from 'next/font/google'
import './globals.css'
import { Providers } from './Providers';
import 'simplebar-react/dist/simplebar.min.css';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Providers>
        <body className={inter.className} style={{ marginTop: "0px" , marginLeft: "-8px", marginRight: "-8px"}}>
        {children}
        </body>
      </Providers>
    </html>
  )
}
